name: Deploy AWS

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write

    steps:
      - name: Clone do projeto
        uses: actions/checkout@v4
        
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "youcancallmegus"
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: youcancallmegus/movimentacoes-ci:${{ github.sha }}

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_TEST }}
          username: "ubuntu"
          key: ${{ secrets.KEY_TEST }}
          port: 22
          script: |
            docker stop stocks
            docker rm --force stocks
            docker run -d -p 8080:8080 --name movimentações youcancallmegus/movimentacoes-ci:${{ github.sha }}

      # - name: Install dependencies
      #   run: pip install -r requirements.txt

      # - name: Run tests 
      #   run: pytest --cov=. --cov-report=xml --cov-report=term --cov-report=html --cov-fail-under=90
